name: Notify on Star

on:
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --header "Accept: application/vnd.github.v3+json" \
          --data "{\"title\":\"New star received!\",\"body\":\"${{ github.actor }} just starred your repository ${{ github.repository }}.\"}"
