name: Notify on Star

on:
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      env:
        REPO: ${{ github.repository }}
        ACTOR: ${{ github.actor }}
      run: |
        curl \
        -X POST \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$REPO/issues" \
        -d "{\"title\":\"New star received!\", \"body\":\"$ACTOR just starred your repository $REPO.\"}"
